(ns demo.handlers
  (:require [ascolais.sfere :as sfere]
            [ascolais.twk :as twk]
            [demo.views :as views]
            [demo.system :as system]))

(defn index
  "GET / - Serve the initial lobby page."
  [_request]
  {:status 200
   :headers {"content-type" "text/html"}
   :body (views/lobby-page)})

;; Note: join is now generated by kaiin from lobby-registry metadata
;; See demo.registry for the :lobby/join action

(defn sse-connect
  "POST /sse - Establish persistent SSE connection.
   This is triggered by data-init in lobby-ui."
  [{:keys [signals]}]
  (tap> {:handler :sse-connect :signals signals :system system/*system*})
  (let [username (:username signals)]
    (tap> {:handler :sse-connect :username username})
    (if (or (nil? username) (empty? username))
      (do
        (tap> {:handler :sse-connect :result :username-required})
        {:status 400 :body "Username required"})
      (let [user-key [::sfere/default-scope [:lobby username]]
            store (:store system/*system*)
            existing-keys (sfere/list-connections store [:* [:lobby :*]])
            existing-users (->> existing-keys
                                (map (fn [[_scope [_cat uname]]] uname))
                                (remove #{username}))
            response {::sfere/key [:lobby username]
                      ::twk/fx
                      (concat
                       ;; Send existing participants to the new user
                       (when (seq existing-users)
                         [[::twk/patch-elements
                           (into [:div] (map views/participant-item existing-users))
                           {twk/selector "#participant-list" twk/patch-mode twk/pm-append}]])
                       ;; Broadcast new user to others
                       [[::sfere/broadcast {:pattern [:* [:lobby :*]]
                                            :exclude #{user-key}}
                         [::twk/patch-elements (views/participant-item username)
                          {twk/selector "#participant-list" twk/patch-mode twk/pm-append}]]
                        ;; Broadcast join message to all
                        [::sfere/broadcast {:pattern [:* [:lobby :*]]}
                         [::twk/patch-elements
                          [:div.message.system-message (str username " joined the lobby")]
                          {twk/selector "#messages" twk/patch-mode twk/pm-append}]]])}]
        (tap> {:handler :sse-connect :result :success :response response})
        response))))

;; Note: send-message is now generated by kaiin from lobby-registry metadata
;; See demo.registry for the action definition

;; Note: leave is now generated by kaiin from lobby-registry metadata
;; The :lobby/leave action returns sfere effects directly (no target)
;; See demo.registry for the :lobby/leave action
